name: 's3'
version: '3.8'
services:
    minio:
        image: bitnami/minio:latest
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /bitnami/minio/data --console-address ":9001"
        volumes:
            - minio-s3:/bitnami/minio/data
        labels:
            - "traefik.enable=true"
            # MinIO API (S3 compatible)
            - "traefik.http.routers.minio-api.rule=Host(`s3.cmnw.ru`)"
            - "traefik.http.routers.minio-api.entrypoints=web,websecure"
            - "traefik.http.routers.minio-api.service=minio-api"
            - "traefik.http.services.minio-api.loadbalancer.server.port=9000"

            # MinIO Console (optional - you can access via console.s3.cmnw.ru)
            - "traefik.http.routers.minio-console.rule=Host(`console.s3.cmnw.ru`)"
            - "traefik.http.routers.minio-console.entrypoints=web,websecure"
            - "traefik.http.routers.minio-console.service=minio-console"
            - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
        networks:
            - traefik

volumes:
    minio-s3:
        driver: local

networks:
    traefik:
        external: true
