name: 's3'
version: '3.8'
services:
    minio:
        image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /bitnami/minio/data --console-address ":9001"
        volumes:
            - minio-s3:/bitnami/minio/data
        networks:
            - traefik

volumes:
    minio-s3:
        driver: local

networks:
    traefik:
        external: true
