name: 'gitlab'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - "8083:80"
      - "8443:443"
    shm_size: 2g
    volumes:
      - git_config:/etc/gitlab
      - git_data:/var/opt/gitlab
      - git_logs:/var/log/gitlab
    environment:
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
      # SMTP Configuration
      SMTP_ADDRESS: ${SMTP_ADDRESS}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      GITLAB_EMAIL_FROM: ${GITLAB_EMAIL_FROM}
      GITLAB_EMAIL_REPLY_TO: ${GITLAB_EMAIL_REPLY_TO}
      # Database Configuration
      GITLAB_DB_PASSWORD: ${GITLAB_DB_PASSWORD}
      # Redis Configuration
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      # S3/MinIO Configuration
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      # Backup S3 Configuration
      BACKUP_S3_ACCESS_KEY: ${BACKUP_S3_ACCESS_KEY}
      BACKUP_S3_SECRET_KEY: ${BACKUP_S3_SECRET_KEY}
      BACKUP_S3_ENDPOINT: ${BACKUP_S3_ENDPOINT}
    networks:
      - cmnw

networks:
  cmnw:
    external: true

volumes:
  git_config:
    name: git_config
  git_data:
    name: git_data
  git_logs:
    name: git_logs
