name: 'home'
version: '3.8'
services:
  home-assistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      # Uncomment the line below if you need D-Bus for Bluetooth or other integrations
      # - /var/run/dbus:/var/run/dbus:ro
    ports:
      - "8123:8123"
    environment:
      - TZ=${TZ}
    privileged: true # This can be useful for certain hardware integrations, but use with caution. Consider 'devices' for specific hardware passthrough instead.
    restart: unless-stopped
    network_mode: host # Recommended for easier device discovery and integrations. If you use 'bridge' mode, you'll need to map all necessary ports.
    # If you need to pass through specific USB devices (e.g., Zigbee/Z-Wave dongle), add them here:
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    command: "mosquitto -c /mosquitto-no-auth.conf"
    volumes:
      - mosquitto:/mosquitto/config
      - mosquitto:/mosquitto/data
      - mosquitto:/mosquitto/log
    ports:
      - "1883:1883" # MQTT
      # - "9001:9001"
      # Websockets for MQTT
    restart: unless-stopped

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=${TZ}
    volumes:
      -  node-red:/data
    ports:
      - "1880:1880"
    depends_on:
      - home-assistant
      - mosquitto
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    # devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB1

  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    env_file:
      - stack.env
      # devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      # - '/dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D054242-if00:/dev/zwave'
      # run this command: ls -l /dev/serial/by-id/*
    volumes:
      - zwavejsui:/usr/src/app/store
    ports:
      - "8091:8091" # port for web interface

  influxdb:
    container_name: influxdb
    image: influxdb:2
    restart: unless-stopped
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    env_file:
      - stack.env
    ports:
      - "8086:8086"

volumes:
  home-assistant:
  node-red:
  zigbee2mqtt:
  zwavejsui:
  mosquitto:
  influxdb-data:
  influxdb-config:
