name: 'jobs'
version: '3.8'
services:
    rabbitmq:
        image: rabbitmq:3.11.11-management-alpine
        hostname: rabbitmq
        container_name: rabbitmq
        restart: always
        networks:
            - oraculum
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
        volumes:
            - ./volumes/rabbitmq:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"

networks:
    oraculum:
        driver: bridge
