name: 'ai'
version: '3.8'

services:
  github-mcp-server:
    image: ghcr.io/github/github-mcp-server
    container_name: github-mcp-server
    environment:
      MCP_SERVER_NAME: github
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3001:3000"
    volumes:
      - mcp-github-data:/data
    restart: always
    networks:
      - cmnw

  mcp-grafana:
    container_name: mcp-grafana
    image: mcp/grafana:latest
    restart: always
    environment:
      GRAFANA_URL: ${GRAFANA_URL}
      GRAFANA_SERVICE_ACCOUNT_TOKEN: ${GRAFANA_SERVICE_ACCOUNT_TOKEN}
    ports:
      - "8001:8001"
    command: ["--transport", "sse", "--address", "0.0.0.0:8001"]
    networks:
      - cmnw

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3080:8080"      # Web UI
    environment:
      OPENAI_API_BASE_URL: ${OPENROUTER_BASE_URL}
      OPENAI_API_KEY: ${OPENROUTER_API_KEY}
      WEBUI_AUTH: ${WEBUI_AUTH}
    volumes:
      - open-webui:/app/backend/data
    networks:
      - cmnw
    security_opt:
      - no-new-privileges:true

volumes:
  mcp-github-data:
    driver: local

  open-webui:
    driver: local

networks:
  cmnw:
    external: true
