name: 'gitlab'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - "8083:80"
      - "8443:443"
      - "2222:22"
    shm_size: 2g
    volumes:
      - git_config:/etc/gitlab
      - git_data:/var/opt/gitlab
      - git_logs:/var/log/gitlab
    environment:
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    networks:
      - cmnw

networks:
  cmnw:
    external: true

volumes:
  git_config:
    name: git_config
  git_data:
    name: git_data
  git_logs:
    name: git_logs
