http:
    middlewares:
        dashboard-auth:
            basicAuth:
                users:
                    - "cmnw:$apr1$x/FfMBS4$LzgWrT7L5kaX11gpjuKRR."
    routers:
        api:
            rule: "Host(`localhost`)"
            entrypoints: ["web"]
            middlewares: ["dashboard-auth"]
            service: "api@internal"
