providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        # network: frontend # Optional; Only use the "proxy" Docker network, even if containers are on multiple networks.
        watch: true
    file:
        filename: /etc/traefik/dynamic.yml
        watch: true

certificatesResolvers:
    letencrypt:
        acme:
            email: cmnw@protonmail.com
            storage: /etc/traefik/acme.json
            # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
            caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
            httpChallenge:
                entryPoint: web

entryPoints:
    web:
        address: ":80"
    # Optional if you want to redirect all HTTP to HTTPS
    #  http:
    #    redirections:
    #      entryPoint:
    #        to: websecure
    #        scheme: https

api:
    dashboard: true # Optional can be disabled
    insecure: false # Optional can be disabled
    debug: false # Optional can be Enabled if needed for troubleshooting
