# traefik-static.yml - Static configuration file
# This replaces all the command line arguments

# Global configuration
global:
    checkNewVersion: false
    sendAnonymousUsage: false

# API and Dashboard
api:
    dashboard: true
    insecure: false

# Entry Points
entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entrypoint:
                    to: websecure
                    scheme: https
                    permanent: true

    websecure:
        address: ":443"

    traefik:
        address: ":8080"

    metrics:
        address: ":8082"

# Providers
providers:
    # Docker provider
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
        watch: true

    # File provider for dynamic configuration
    file:
        filename: /etc/traefik/traefik-dynamic.yml
        watch: true

# REMOVED: Certificate Resolvers section since we're using static certificates
# The certificates will be defined in the dynamic configuration file

# Logging
log:
    level: INFO
    filePath: /var/log/traefik/traefik.log

# Access logs
accessLog:
    filePath: /var/log/traefik/access.log
    bufferingSize: 100

# Metrics
metrics:
    prometheus:
        addEntryPointsLabels: true
        addServicesLabels: true
        addRoutersLabels: true
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0

# Ping endpoint for health checks
ping:
    entryPoint: traefik

# Tracing (optional)
# tracing:
#   jaeger:
#     samplingServerURL: http://jaeger:14268/sampling
#     localAgentHostPort: jaeger:6831

# Cluster store (optional, for HA setups)
# cluster:
#   store: consul
#   prefix: traefik
